services:
  medipal-db:
    image: mysql:8.0
    container_name: medipal_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medipal_db
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql